### ISSUE TITLE
Change the address of the Goerli resolver

### ISSUE THREAD

**Issue by nazariyv** [superfluid-finance/superfluid-protocol-preview#6]
The tutorial here: https://docs.superfluid.finance/tutorials/instant-distribution/
uses the following resolver address `0xDC200aA39Aa1D9B28CE458979602eb79046A1C9f`
however `ethereum-contracts/js-sdk/getConfig.js` uses `0x3710AB3fDE2B61736B8BB0CE845D6c61F667a78E` which does not resolve any addresses. Switching this to `0xDC200aA39Aa1D9B28CE458979602eb79046A1C9f` solves the issue

**Comment by ngmachado** [comment]
Hi, updated the docs.

The resolver ~~0xDC200aA39Aa1D9B28CE458979602eb79046A1C9f~~ is relative to version "preview-20200928".

Please use the new version "0.1.2-preview-20201014" and you get the following data: 

> Resolver at 0x3710AB3fDE2B61736B8BB0CE845D6c61F667a78E
> Resolving contracts with version 0.1.2-preview-20201014
> Superfluid 0x8EA403f69173CB3271DBBa1916DD99d8E294B46f
> ConstantFlowAgreementV1 0x270a86E3F664b4c6db6a1CD6f7309Ca2E468Fc85
> InstantDistributionAgreementV1 0x265F42856aF54ff630B3C6297d4d125f9c8ED60f


[Instant Distribution Tutorial](https://github.com/superfluid-finance/superfluid-protocol-docs/blob/source/content/tutorials/instant-distribution/index.mdx).

**Comment by vbstreetz** [comment]
> 0.1.2-preview-20201014

This still doesn't work for me 🤔

**Comment by vbstreetz** [comment]
my bad. `GOERLI_PROVIDER_URL` was incorrectly set to `https://mainnet.infura.io/...` instead of `https://goerli.infura.io/...`
